FROM microsoft/dotnet:2.1-sdk
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["Helm.Site/Helm.Site.csproj", "Helm.Site/"]

RUN dotnet restore "Helm.Site/Helm.Site.csproj"
COPY . .
WORKDIR "/src/Helm.Site"
RUN dotnet build --no-restore "Helm.Site.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-restore", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]